"""rename address

Revision ID: b8a16af3ec50
Revises: dfec9934a40e
Create Date: 2024-10-02 23:46:17.857304

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b8a16af3ec50'
down_revision = 'dfec9934a40e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
   op.alter_column('departments','address', new_column_name='location')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('departments','location', new_column_name='address')
    # ### end Alembic commands ###
