"""rename department

Revision ID: dfec9934a40e
Revises: 0f0b6f2c9d26
Create Date: 2024-10-02 23:29:01.891639

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dfec9934a40e'
down_revision = '0f0b6f2c9d26'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.rename_table('department','departments')
    # ### end Alembic commands ###


def downgrade():
   op.rename_table('departments','department')
